{{- if .Values.backup.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-s3-creds
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  ACCESS_KEY_ID: {{ .Values.backup.s3.accessKey }}
  SECRET_ACCESS_KEY: {{ .Values.backup.s3.secretKey }}
{{- end }}